import turtle

screen = turtle.Screen()
screen.setup(500, 500)
screen.bgcolor('aquamarine')

eternaldamnation = turtle.Turtle()
eternaldamnation.speed(0)
eternaldamnation.hideturtle()
transientsalvation = turtle.Turtle()
transientsalvation.speed(0)
transientsalvation.hideturtle()
desolatevoid = turtle.Turtle()
desolatevoid.speed(0)
desolatevoid.hideturtle()

#page 1: intro
screen.bgcolor('aquamarine')
transientsalvation.fillcolor('silver')
eternaldamnation.penup()
eternaldamnation.goto(0, 50)
eternaldamnation.pendown()
eternaldamnation.write("All About Katelynn",font=('lora',30,'italic'),align="center")
eternaldamnation.penup()
eternaldamnation.goto(0, -50)
eternaldamnation.pendown()
eternaldamnation.write("Press Enter to begin :)", font=('lora', 20, 'bold'), align="center")

desolatevoid.penup()
turtle.addshape("me.gif")
desolatevoid.shape("me.gif")
desolatevoid.goto(-150,150)
a = desolatevoid.stamp()
turtle.addshape("helios.gif")
desolatevoid.shape("helios.gif")
desolatevoid.goto(150,-150)
b = desolatevoid.stamp()

transientsalvation.penup()
transientsalvation.goto(-200, -200)
transientsalvation.pendown()
transientsalvation.pencolor('red')
transientsalvation.begin_fill()
transientsalvation.forward(100)
transientsalvation.left(90)
transientsalvation.forward(100)
transientsalvation.left(90)
transientsalvation.forward(100)
transientsalvation.left(90)
transientsalvation.forward(100)
transientsalvation.end_fill()


enter = input("Press Enter to begin")
eternaldamnation.clear()
transientsalvation.clear()
desolatevoid.clearstamps()

#page 2: foods
screen.bgcolor('green')
transientsalvation.fillcolor('mediumpurple')
eternaldamnation.penup()
eternaldamnation.goto(0, 50)
eternaldamnation.pendown()
eternaldamnation.write("Favorite Foods",font=('lora',30,'italic'),align="center")
eternaldamnation.penup()
eternaldamnation.goto(0, -50)
eternaldamnation.pendown()
eternaldamnation.write("1. Crab legs\n2. Pie\n3. Cheesecake", font=('lora', 20, 'bold'), align="center")
eternaldamnation.penup()
eternaldamnation.goto(0, -250)
eternaldamnation.pendown()
eternaldamnation.write("Press Enter to Continue", font=('lora', 20), align="center")

desolatevoid.penup()
turtle.addshape("crab.gif")
desolatevoid.shape("crab.gif")
desolatevoid.goto(-150,150)
a = desolatevoid.stamp()
turtle.addshape("pie.gif")
desolatevoid.shape("pie.gif")
desolatevoid.goto(150,-150)
b = desolatevoid.stamp()
turtle.addshape("cheesecake.gif")
desolatevoid.shape("cheesecake.gif")
desolatevoid.goto(150,150)
c = desolatevoid.stamp()

transientsalvation.penup()
transientsalvation.goto(-200, -120)
transientsalvation.pendown()
transientsalvation.begin_fill()
transientsalvation.forward(50)
transientsalvation.left(45)
transientsalvation.forward(50)
transientsalvation.left(45)
transientsalvation.forward(50)
transientsalvation.left(45)
transientsalvation.forward(50)
transientsalvation.left(45)
transientsalvation.forward(50)
transientsalvation.left(45)
transientsalvation.forward(50)
transientsalvation.left(45)
transientsalvation.forward(50)
transientsalvation.left(45)
transientsalvation.forward(50)
transientsalvation.left(45)
transientsalvation.end_fill()

enter = input("Press Enter to continue")
eternaldamnation.clear()
transientsalvation.clear()
desolatevoid.clearstamps()

#page 3: hobbies
screen.bgcolor('silver')
transientsalvation.fillcolor('hotpink')
eternaldamnation.penup()
eternaldamnation.goto(0, 70)
eternaldamnation.pendown()
eternaldamnation.write("Hobbies",font=('lora',30,'italic'),align="center")
eternaldamnation.penup()
eternaldamnation.goto(0, -80)
eternaldamnation.pendown()
eternaldamnation.write("1. Writing\n2. Dance\n3. Reading\n4. Musical Theater", font=('lora', 20, 'bold'), align="center")
eternaldamnation.penup()
eternaldamnation.goto(0, -250)
eternaldamnation.pendown()
eternaldamnation.write("Press Enter to Continue", font=('lora', 20), align="center")

desolatevoid.penup()
turtle.addshape("writing.gif")
desolatevoid.shape("writing.gif")
desolatevoid.goto(-150,150)
a = desolatevoid.stamp()
turtle.addshape("dance.gif")
desolatevoid.shape("dance.gif")
desolatevoid.goto(150,-150)
b = desolatevoid.stamp()
turtle.addshape("books.gif")
desolatevoid.shape("books.gif")
desolatevoid.goto(150,150)
c = desolatevoid.stamp()
turtle.addshape("theater.gif")
desolatevoid.shape("theater.gif")
desolatevoid.goto(-50,-150)
d = desolatevoid.stamp()

transientsalvation.penup()
transientsalvation.goto(-200, -210)
transientsalvation.pendown()
transientsalvation.begin_fill()
transientsalvation.circle(25)
transientsalvation.end_fill()

enter = input("Press Enter to continue")
eternaldamnation.clear()
transientsalvation.clear()
desolatevoid.clearstamps()

#page 4: movie
screen.bgcolor('dodgerblue')
transientsalvation.fillcolor('cornsilk')
eternaldamnation.penup()
eternaldamnation.goto(0, 50)
eternaldamnation.pendown()
eternaldamnation.write("Favorite Movie",font=('lora',30,'italic'),align="center")
eternaldamnation.penup()
eternaldamnation.goto(0, -50)
eternaldamnation.pendown()
eternaldamnation.write("Wicked", font=('lora', 20, 'bold'), align="center")
eternaldamnation.penup()
eternaldamnation.goto(0, -250)
eternaldamnation.pendown()
eternaldamnation.write("Press Enter to Continue", font=('lora', 20), align="center")

desolatevoid.penup()
turtle.addshape("wickedone.gif")
desolatevoid.shape("wickedone.gif")
desolatevoid.goto(-150,150)
a = desolatevoid.stamp()
turtle.addshape("wickedtwo.gif")
desolatevoid.shape("wickedtwo.gif")
desolatevoid.goto(150,-150)
b = desolatevoid.stamp()

transientsalvation.penup()
transientsalvation.goto(-200, -150)#1
transientsalvation.pendown()
transientsalvation.setheading(0)

transientsalvation.begin_fill()
transientsalvation.goto(-175,-135)#2
transientsalvation.goto(-187,-100)#3
transientsalvation.goto(-200,-150)#1
transientsalvation.end_fill()

enter = input("Press Enter to continue")
eternaldamnation.clear()
transientsalvation.clear()
desolatevoid.clearstamps()

#page 5: sport
screen.bgcolor('orange')
transientsalvation.fillcolor('darkgray')
eternaldamnation.penup()
eternaldamnation.goto(0, 50)
eternaldamnation.pendown()
eternaldamnation.write("Favorite Sport",font=('lora',30,'italic'),align="center")
eternaldamnation.penup()
eternaldamnation.goto(0, -50)
eternaldamnation.pendown()
eternaldamnation.write("Hockey", font=('lora', 20, 'bold'), align="center")
eternaldamnation.penup()
eternaldamnation.goto(0, -250)
eternaldamnation.pendown()
eternaldamnation.write("Press Enter to Continue", font=('lora', 20), align="center")

desolatevoid.penup()
turtle.addshape("pens.gif")
desolatevoid.shape("pens.gif")
desolatevoid.goto(-150,150)
a = desolatevoid.stamp()
turtle.addshape("crosby.gif")
desolatevoid.shape("crosby.gif")
desolatevoid.goto(150,-150)
b = desolatevoid.stamp()

transientsalvation.penup()
transientsalvation.goto(-200, -200)
transientsalvation.pendown()
transientsalvation.begin_fill()
transientsalvation.circle(30, 180)
transientsalvation.end_fill()


enter = input("Press Enter to continue")
eternaldamnation.clear()
transientsalvation.clear()
desolatevoid.clearstamps()

